SUCCESS_CODE_MAX_INT = (10 ** 16 - 1)
SUCCESS_CODE_MAX_INT_LENGTH = len(str(SUCCESS_CODE_MAX_INT))

DATE_FORMAT = "%d%m%Y"
DATE_LENGTH = 8

USERNAME_MAX_INT = (10 ** 16 - 1)
USERNAME_MAX_INT_LENGTH = len(str(USERNAME_MAX_INT))

PASSWORD_MAX_INT = (10 ** 65 - 1)
PASSWORD_MAX_INT_LENGTH = len(str(PASSWORD_MAX_INT))